import chroma from "chroma-js";
import { getColorTheme } from "./getColorTheme";

const SECOND_THOUGHTS_ACCENT_COLOR = chroma("#f05122")
  .darken(0.8)
  .saturate(-0.7)
  .hex();

const SECOND_THOUGHTS_BACKGROUND_COLOR = chroma("#f05122")
  .mix("#000000", 0.97)
  .hex();

const SECOND_THOUGHTS_ALBUM_NAME_COLOR = chroma(SECOND_THOUGHTS_ACCENT_COLOR)
  .alpha(0.45)
  .css();

const SECOND_THOUGHTS_SONG_NAME_COLOR = chroma("#f05122")
  .darken(0.5)
  .saturate(0.6)
  .hex();

const SECOND_THOUGHTS_SONG_AUTHOR_COLOR = chroma(SECOND_THOUGHTS_ACCENT_COLOR)
  .alpha(1)
  .css();
const SECOND_THOUGHTS_SONG_DURATION_COLOR = SECOND_THOUGHTS_ACCENT_COLOR;

const SECOND_THOUGHTS_ACTIVE_SONG_SONG_NAME_COLOR = "#222222";

const SECOND_THOUGHTS_ACTIVE_SONG_SONG_AUTHOR_COLOR = chroma(
  SECOND_THOUGHTS_ACCENT_COLOR,
)
  .mix(SECOND_THOUGHTS_BACKGROUND_COLOR, 0.7)
  .hex();

const SECOND_THOUGHTS_ACTIVE_SONG_SONG_DURATION_COLOR = chroma(
  SECOND_THOUGHTS_ACCENT_COLOR,
)
  .mix(SECOND_THOUGHTS_BACKGROUND_COLOR, 0.7)
  .hex();

const SECOND_THOUGHTS_ALBUM_BOX_SHADOW_COLOR = chroma("#f05122")
  .darken(0.5)
  .saturate(0.8)
  .alpha(0.5)
  .css();

const SECOND_THOUGHTS_WAVE_COLOR = "#FFD166";

export const COLOR_THEME = getColorTheme({
  accent: SECOND_THOUGHTS_ACCENT_COLOR,
  background: SECOND_THOUGHTS_BACKGROUND_COLOR,
  songName: SECOND_THOUGHTS_SONG_NAME_COLOR,
  authorName: SECOND_THOUGHTS_SONG_AUTHOR_COLOR,
  duration: SECOND_THOUGHTS_SONG_DURATION_COLOR,
  activeSongName: SECOND_THOUGHTS_ACTIVE_SONG_SONG_NAME_COLOR,
  activeSongAuthor: SECOND_THOUGHTS_ACTIVE_SONG_SONG_AUTHOR_COLOR,
  activeSongDuration: SECOND_THOUGHTS_ACTIVE_SONG_SONG_DURATION_COLOR,
  albumShadow: SECOND_THOUGHTS_ALBUM_BOX_SHADOW_COLOR,
  albumNameColor: SECOND_THOUGHTS_ALBUM_NAME_COLOR,
  waveColor: SECOND_THOUGHTS_WAVE_COLOR,
});
