import chroma from "chroma-js";
import { getColorTheme } from "./getColorTheme";

const STRICTLY_BB_ACCENT_COLOR = "#FEFCAF";
const STRICTLY_BB_BACKGROUND_COLOR = "#020100";

// ALBUM NAME
const STRICTLY_BB_ALBUM_NAME_COLOR = chroma(STRICTLY_BB_ACCENT_COLOR)
  .alpha(0.45)
  .css();

// SONG
const STRICTLY_BB_SONG_NAME_COLOR = chroma(STRICTLY_BB_ACCENT_COLOR)
  .alpha(1)
  .css();
const STRICTLY_BB_SONG_AUTHOR_COLOR = chroma(STRICTLY_BB_ACCENT_COLOR)
  .alpha(0.7)
  .css();
const STRICTLY_BB_SONG_DURATION_COLOR = STRICTLY_BB_ACCENT_COLOR;

const STRICTLY_BB_ACTIVE_SONG_SONG_NAME_COLOR = chroma(STRICTLY_BB_ACCENT_COLOR)
  .mix(STRICTLY_BB_BACKGROUND_COLOR, 0.9)
  .hex();

const STRICTLY_BB_ACTIVE_SONG_SONG_AUTHOR_COLOR = chroma(
  STRICTLY_BB_ACCENT_COLOR,
)
  .mix(STRICTLY_BB_BACKGROUND_COLOR, 0.7)
  .hex();

const STRICTLY_BB_ACTIVE_SONG_SONG_DURATION_COLOR = chroma(
  STRICTLY_BB_ACCENT_COLOR,
)
  .mix(STRICTLY_BB_BACKGROUND_COLOR, 0.7)
  .hex();

const STRICTLY_BB_ALBUM_BOX_SHADOW_COLOR = chroma(STRICTLY_BB_ACCENT_COLOR)
  .alpha(0.22)
  .css();

export const COLOR_THEME = getColorTheme({
  accent: STRICTLY_BB_ACCENT_COLOR,
  background: STRICTLY_BB_BACKGROUND_COLOR,
  songName: STRICTLY_BB_SONG_NAME_COLOR,
  authorName: STRICTLY_BB_SONG_AUTHOR_COLOR,
  duration: STRICTLY_BB_SONG_DURATION_COLOR,
  activeSongName: STRICTLY_BB_ACTIVE_SONG_SONG_NAME_COLOR,
  activeSongAuthor: STRICTLY_BB_ACTIVE_SONG_SONG_AUTHOR_COLOR,
  activeSongDuration: STRICTLY_BB_ACTIVE_SONG_SONG_DURATION_COLOR,
  albumShadow: STRICTLY_BB_ALBUM_BOX_SHADOW_COLOR,
  albumNameColor: STRICTLY_BB_ALBUM_NAME_COLOR,
  waveColor: STRICTLY_BB_ACCENT_COLOR,
});
