import chroma from "chroma-js";
import { getColorTheme } from "./getColorTheme";

const SEMPLICEMENTE_ACCENT_COLOR = "#DAD4CB";
const SEMPLICEMENTE_BACKGROUND_COLOR = "#000000";

// ALBUM NAME
const SEMPLICEMENTE_ALBUM_NAME_COLOR = chroma(SEMPLICEMENTE_ACCENT_COLOR)
  .alpha(0.45)
  .css();

// SONG
const SEMPLICEMENTE_SONG_NAME_COLOR = SEMPLICEMENTE_ACCENT_COLOR;

const SEMPLICEMENTE_SONG_AUTHOR_COLOR = chroma(SEMPLICEMENTE_ACCENT_COLOR)
  .alpha(1)
  .css();
const SEMPLICEMENTE_SONG_DURATION_COLOR = SEMPLICEMENTE_ACCENT_COLOR;

const SEMPLICEMENTE_ACTIVE_SONG_SONG_NAME_COLOR = chroma(
  SEMPLICEMENTE_ACCENT_COLOR,
)
  .mix(SEMPLICEMENTE_BACKGROUND_COLOR, 0.9)
  .hex();

const SEMPLICEMENTE_ACTIVE_SONG_SONG_AUTHOR_COLOR = chroma(
  SEMPLICEMENTE_ACCENT_COLOR,
)
  .mix(SEMPLICEMENTE_BACKGROUND_COLOR, 0.7)
  .hex();

const SEMPLICEMENTE_ACTIVE_SONG_SONG_DURATION_COLOR = chroma(
  SEMPLICEMENTE_ACCENT_COLOR,
)
  .mix(SEMPLICEMENTE_BACKGROUND_COLOR, 0.7)
  .hex();

const SEMPLICEMENTE_ALBUM_BOX_SHADOW_COLOR = chroma(SEMPLICEMENTE_ACCENT_COLOR)
  .alpha(0.22)
  .css();

export const COLOR_THEME = getColorTheme({
  accent: SEMPLICEMENTE_ACCENT_COLOR,
  background: SEMPLICEMENTE_BACKGROUND_COLOR,
  songName: SEMPLICEMENTE_SONG_NAME_COLOR,
  authorName: SEMPLICEMENTE_SONG_AUTHOR_COLOR,
  duration: SEMPLICEMENTE_SONG_DURATION_COLOR,
  activeSongName: SEMPLICEMENTE_ACTIVE_SONG_SONG_NAME_COLOR,
  activeSongAuthor: SEMPLICEMENTE_ACTIVE_SONG_SONG_AUTHOR_COLOR,
  activeSongDuration: SEMPLICEMENTE_ACTIVE_SONG_SONG_DURATION_COLOR,
  albumShadow: SEMPLICEMENTE_ALBUM_BOX_SHADOW_COLOR,
  albumNameColor: SEMPLICEMENTE_ALBUM_NAME_COLOR,
  waveColor: SEMPLICEMENTE_ACCENT_COLOR,
});
